import sys
import asyncio
from app_modules.chatgpt_page import ChatGPTPage

async def get_async_stdin_fallback(prompt_text: str) -> str:
    """Helper to interrupt the core loop for recovery input via standard input."""
    print(prompt_text, end="", flush=True)
    return await asyncio.get_event_loop().run_in_executor(None, sys.stdin.readline)

async def execute_chat_transaction(chat_page: ChatGPTPage, user_message: str) -> str:
    """
    Pure automation service loop.
    Enforces rules, handles element failure, and waits for a manual fix if blocked.
    Returns the string text generated by the browser.
    """
    strict_text_rule = " (Respond strictly in completely raw plain text paragraphs. Do not use markdown bullet lists, bolding asterisks, headers, or block quotes.)"
    final_prompt = user_message + strict_text_rule

    while True:
        try:
            # 1. Type the message
            await chat_page.prepare_and_type_prompt(final_prompt)
            
            # 2. Get the snapshot index for extraction
            target_index = await chat_page.get_assistant_turn_count()
            
            # 3. Fire message payload
            await chat_page.click_send()
            
            # 4. Extract generated string block cleanly
            output_string = await chat_page.wait_and_extract_response(target_index)
            return output_string
            
        except Exception as e:
            print(f"\n[⚠️ CORE SERVICE EXCEPTION]: {type(e).__name__} - {str(e)}")
            print("[!] Browser automation path was blocked by layout state.")
            await get_async_stdin_fallback("[Terminal Recovery] Resolve the blockage in Chrome, then press ENTER to retry payload... ")
